### ISSUE TITLE
Length of the numbers lead to wrong sorting

### ISSUE THREAD

**Issue by scimax** [SethMMorton/natsort#101]
Dear all,
I experienced the following issue:

**Describe the bug**
The sorting is wrong with respect to the float numbers in the string. The length of the floating point number in terms of decimal places affects the outcome. See below in the example

**Expected behavior**
The number of decimal places should not change the ordering of the strings.

**Environment (please complete the following information):**
- natsort 6.0.0
- Python 3.6.6 from the conda-forge channel
 - Windows 10
 - LOCALE is not used

**To Reproduce**
This is the list I tried to sort:
```py
natsorted(['on-axis-ezt=0.900000003596222.txt',
 'on-axis-ezt=1.0000000039958.txt',
 'on-axis-ezt=1.5000000059937.txt',
 'on-axis-ezt=1.10000000439538.txt'])
```

The result was this one:
```py 
['on-axis-ezt=0.900000003596222.txt',
 'on-axis-ezt=1.0000000039958.txt',
 'on-axis-ezt=1.5000000059937.txt',
 'on-axis-ezt=1.10000000439538.txt']
```

If I truncate the decimal places following the dot it works but intuitively I would not expect this to change the outcome, since `1.1000000001 < 1.5`, no matter how many digits follow the decimal seperator.

So it works if I do it this way:
```py
natsorted(['on-axis-ezt=0.900.txt',
 'on-axis-ezt=1.000.txt',
 'on-axis-ezt=1.500.txt',
 'on-axis-ezt=1.100.txt'])
```
but adding a single 0 before the file extension in the last string screws up the result. I thougt it might be related to my OS settings using comma as decimal seperator although I'm not using the LOCALE in the natsort package. But the behavior is the same if I replace the dot with a comma.

I also tried to split the sttrings first and only use the part containing the floating point numbers, so something like that `os.path.splitext(filename)[0].split("=")[1]` but it also didn't change anything

**Comment by SethMMorton** [comment]
[As described in the README](https://github.com/SethMMorton/natsort#sorting-by-real-numbers-ie-signed-floats), please use [`realsorted`](https://natsort.readthedocs.io/en/master/api.html#natsort.realsorted) or the [`ns.REAL`](https://natsort.readthedocs.io/en/master/api.html#the-ns-enum) setting for the `alg` option.
