### ISSUE TITLE
test_sep_inserter_inserts_separator_between_two_numbers fails

### ISSUE THREAD

**Issue by mcepl** [SethMMorton/natsort#108]
**Describe the bug**
Irregularly and on some minor architectures (i586, ppc64le) the test test_sep_inserter_inserts_separator_between_two_numbers fails from time to time with this:
```
[  185s] =================================== FAILURES ===================================
[  185s] ___________ test_sep_inserter_inserts_separator_between_two_numbers ____________
[  185s] 
[  185s]     @given(lists(elements=text().filter(bool) | integers(), min_size=3))
[  185s] >   def test_sep_inserter_inserts_separator_between_two_numbers(x):
[  185s] E   hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 0 valid examples in 1.05 seconds (5 invalid ones and 2 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.max_size or max_leaves parameters).
[  185s] E   See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.
[  185s] 
[  185s] tests/test_utils.py:121: FailedHealthCheck
[  185s] ---------------------------------- Hypothesis ----------------------------------
[  185s] You can add @seed(329818451744358783807391397008596432428) to this test or run pytest with --hypothesis-seed=329818451744358783807391397008596432428 to reproduce this failure.
[  185s] ====== 1 failed, 264 passed, 7 skipped, 6 deselected in 118.97s (0:01:58) ======
```

**Expected behavior**
ALl tests should pass (and ignoring #107 for a moment).

**Environment (please complete the following information):**
 - Python Version: 3.7.3
 - OS openSUSE/Tumbleweed (in fact building the official packages for it)
 - If the bug involves `LOCALE` or `humansorted`:
    - Is `PyICU` installed? No
    - Do you have a locale set? If so, to what? Yes, ``export LANG=en_US.UTF8``
      is run before the tests are run.

**To Reproduce**
See above.

It seems to me that suppressing health heck of ``hypothesis.HealthCheck.too_slow`` is too optimistic and that line should be just elimnated from ``conftest.py``.

[Full build log with all details](https://github.com/SethMMorton/natsort/files/3993124/_log.txt) (includes list of all installed packages as well with their versions)

**Comment by SethMMorton** [comment]
This is related to https://github.com/HypothesisWorks/hypothesis/issues/2195. Long story short, the `hypothesis` devs recommended to me that I suppress this health check to prevent `hypothesis` from failing my tests erroneously.

Additionally, it looks like you are using `hypothesis` version 4.53.2. I have `hypothesis` pinned to 4.44.2 in the `dev/requirements.txt` file. It *may* be that this would eliminate the failure, but on the other hand it may be that this is one of those things that sometimes passes and sometimes fails (much to my chagrin). Can you try using the pinned testing dependencies?

**Comment by mcepl** [comment]
Of course, the reply is the same as in https://github.com/SethMMorton/natsort/issues/107#issuecomment-568424211.

**Comment by SethMMorton** [comment]
Just out of curiosity, why do you think that removing the suppression of the "too slow" health check would get rid of the "too slow" failure?

**Comment by SethMMorton** [comment]
Also, I realize now (looking at your build log) that the "too slow" health check suppression was not actually activated in your tests. To do that, you need to add `--hypothesis-profile=slow-tests` to your `pytest` invocation.

**Comment by SethMMorton** [comment]
I hope to release version 7.0.0 of `natsort` within the next few days. I do not believe that any change on my end is needed for this (because addition of the `--hypothesis-profile=slow-tests` option should fix it) but I want to get verification from you that this in fact solves the problem. Once I get verification I will make the release.

**Comment by mcepl** [comment]
Running ``py.test-3.7 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v --hypothesis-profile=slow-tests`` leads to the error:
```
hypothesis.errors.InvalidArgument: Profile 'slow-tests' is not registered
```

**Comment by SethMMorton** [comment]
I am going to assume this is working and release `natsort` 7.0.0.

**Comment by mcepl** [comment]
Thank you, [pushed to Factory](https://build.opensuse.org/request/show/762091).
