### ISSUE TITLE
Pandas 1.1.0 started to support `key` parameter

### ISSUE THREAD

**Issue by kuraga** [SethMMorton/natsort#115]
Pandas 1.1.0 [started to support `key` parameter](https://github.com/pandas-dev/pandas/blob/d9fff2792bf16178d4e450fe7384244e50635733/doc/source/whatsnew/v1.1.0.rst#sorting-with-keys). So, let's reflect it [here](https://github.com/SethMMorton/natsort/blob/7c9d01545a9cfd9ac3c0485183cb6ed9ec956837/docs/examples.rst#L401)?

**Comment by SethMMorton** [comment]
Sounds great! Would you be willing to submit a PR to get the ball rolling?
