### ISSUE TITLE
Incomplete date sort issue

### ISSUE THREAD

**Issue by bazuchan** [SethMMorton/natsort#129]
**Describe the bug**
I'm sorting albums named as date in format 2021_01_16. Sometimes X is used to indicate period (not just single day), for example 2021_01_2X. Natsort sorts it as numbers, leaving X, so 2021_01_2X appears before 2021_01_16.

**Expected behavior**
['2021_01_16', '2021_01_2X', '2021_01_29'] is sorted in order ['2021_01_16', '2021_01_29', '2021_01_2X'] just like usual sorted()

**Environment (please complete the following information):**
 - Python Version: 3.9
 - OS Ubuntu
 - If the bug involves `LOCALE` or `humansorted`:
    - Is `PyICU` installed? No
    - Do you have a locale set? If so, to what? en_US.UTF-8

**To Reproduce**
```
>>> natsort.natsorted(['2021_01_16', '2021_01_2X', '2021_01_29'])
['2021_01_2X', '2021_01_16', '2021_01_29']

>>> sorted(['2021_01_16', '2021_01_2X', '2021_01_29'])
['2021_01_16', '2021_01_29', '2021_01_2X']
```

**Comment by SethMMorton** [comment]
To be honest, I'm not convinced that you want or need a natural sort here. If this example is representative of all thedata you might be sorting, I would advise to not use `natsort`.

One of the reason the YYYMMDD (or YYYY_MM_DD) format is so popular for dates is that it can be sorted lexicographically, so natural sort algorithms aren't needed.

In your case, you are looking to have the natural sort behave as if it is a standard lexicographical sort when a letter is where a number should be. A natural sort doesn't really work that way, as it pre-processes the data by separating the numbers from the non-numbers *before* sorting (see [How does natsort work?](https://natsort.readthedocs.io/en/master/howitworks.html) for gory details).

If you still really want to use `natsort`, here is a hack that will work for the data you have shown. 

```python
>>> natsort.natsorted(['2021_01_16', '2021_01_2X', '2021_01_29'], key=lambda x: x.replace("X", "00"))
['2021_01_16', '2021_01_29', '2021_01_2X']
```

This will replace "X" with "00", causing "2X" to look like "200", which will cause it to be sorted at the end. Though, it would not put "1X" between "16" and "20". So maybe it's not overly robust.

Here's another hack:

```python
>>> natsort.natsorted(['2021_01_16', '2021_01_2X', '2021_01_29', '2021_01_1X'], alg=natsort.FLOAT, key=lambda x: x.replace("X", "9.9"))
['2021_01_16', '2021_01_1X', '2021_01_29', '2021_01_2X']
```
OK, so this works. It replaces "X" with "9.9", so "2X" becomes "29.9", and it also tells natsort to interpret numbers as floats, not integers, so the decimal is taken into account. This way, an "X" will always be sorted at the end of any 2-digit sequence.

Again, my recommendation would be to just use the built-in `sorted` if this is the only type of data you are sorting. Or, if the picture is bigger and you need `natsort` but have to handle these examples, you can try the second hack, and if that does not work hopefully you can see how I go about customizing the sort, and you can play with keys till you find something that works for you.
