### ISSUE TITLE
Strings ending without a number end up last

### ISSUE THREAD

**Issue by AgostinoSturaro** [SethMMorton/natsort#134]
I was trying to sort something like this
`lines = ['foo2', 'foo3', 'foo1', 'foo']`

I tried various options, including the following
```
import natsort as ns
lines = [...]
lines = ns.natsorted(lines, alg=ns.GROUPLETTERS | ns.LOWERCASEFIRST)
```

And I get this result
`lines = ['foo1', 'foo2', 'foo3', 'foo']`

But what I really want is
`lines = ['foo', 'foo1', 'foo2', 'foo3']`

Is there an option to make prefix strings without the number appear first?
Thank you.

By the way, the actual input is a bit more involved and there is a tab character after the `foo*` strings.
More representative inputs would be
```
lines = ['foo', 'foo1', 'foo2', 'Foo1', 'Foo2', 'foo_1', 'foo_2', 'foo__1', 'foo__2', 'bar', 'bar1', 'bar_2']
lines = ['foo\tbar', 'foo1\tboo', 'foo2\tbaz', 'Foo1\tbuzz', 'Foo2\tbazz', 'bar\tzip', 'bar1\tzopp', 'bar_2\tzapp']
lines = ['foo_a', 'foo_1a', 'foo', 'foo1', 'bar1', 'bar2', 'bar_1a', 'bar_2a', 'bar_1_a', 'bar_2_a', 'bar_2_a1']
```

**Comment by SethMMorton** [comment]
@AgostinoSturaro Did this solve your problem?
