### ISSUE TITLE
Minimal PyIcu install

### ISSUE THREAD

**Issue by maggie0002** [SethMMorton/natsort#136]
I have noted the importance of PyIcu in the documentation and am including it in my Docker container. In an attempt to keep the containers as small as possible I am trying to do as small an install of PyIcu as possible. I started with their docs build procedure:

```
apt-get install pkg-config libicu-dev
pip install --no-binary=:pyicu: pyicu
```

I then removed pkg-config and libicu-dev assuming they were build dependencies. Unfortunately now it’s not working. I have gradually tried adding in packages from within libicu-dev to get it working again but it’s getting complicated and I could end up hitting issues where it looks like it’s working by Natsort is failing. 

Has anyone found a way to use Natsort and reduce the image size? So far the most simplistic I found was to put back this package: https://packages.debian.org/buster/libicu63

To be more specific, I’m only using the os_sorted function. 

A bit of background, all this started because I was building Python from source in my container, and then when installing python3-icu it was installing another version of Python (my source build meant it wasn’t picked up by the package manager). So have been trying to get the image size down by avoiding install of the python3-icu package.

**Comment by SethMMorton** [comment]
I will be of no help here. Hopefully someone from the community has some words of wisdom.

Have you considered asking the PyICU developer this question?

**Comment by maggie0002** [comment]
> I will be of no help here. Hopefully someone from the community has some words of wisdom.
> 
> Have you considered asking the PyICU developer this question?

Thanks for taking the time to drop a message. It's often best to think out loud like this, sometimes someone pops up with something I haven't thought of. 

I have been over to GitLab to poke around the PyICU repo. It's one of those unique circumstances where I don't really have any suggestions for the package to overcome this, it is built like any other package, it might now just be a question of whether my patching will work for Natsort. 

Is there any sort of test I could run with Natsort to check PyICU is working properly? My understanding is the os_sorted function will work with or without PyICU, just more effectively with PyICU. I'm not entirely sure what the difference will be in output using special characters to be able to reproduce a with/without PyICU scenario.

**Comment by SethMMorton** [comment]
PyICU really helps for non-alphanumeric characters. If you are only sorting things within that region then it should be fine without it.

I recommend taking some representative data and sorting without PyICU installed and see if the results make sense.

**Comment by clintonroy** [comment]
Further down, they suggest apt-get install python3-icu

**Comment by clintonroy** [comment]
If you really want to do a source build, do it in a throw away container:

```
FROM debian:bookworm as wheelbuilder
RUN apt-get update
RUN apt-get install -y pkg-config libicu-dev python3-pip
RUN pip install --no-binary=:pyicu: pyicu
RUN pip wheel --wheel-dir=/tmp/ pyicu

FROM debian:bookworm
RUN apt-get update
RUN apt-get install -y python3-pip libicu67
COPY --from=wheelbuilder /tmp/* /tmp/
RUN python3 -m pip install /tmp/PyICU*.whl
```

**Comment by maggie0002** [comment]
Thanks for the thoughts. 

It is for sorting a web-based file manager so there is a chance there will be filenames with non-alphanumeric characters. 

I have done a multi-stage docker build too like the one shown here, but it’s the libicu67 package which takes up the space. Looks like this is the best way to go about it though. So far haven’t encountered any issues, fingers crossed it will stay that way.
