### ISSUE TITLE
Wrong ordering of ordered pandas categoricals 

### ISSUE THREAD

**Issue by arogozhnikov** [SethMMorton/natsort#137]
**Describe the bug**

There is a separate dtype in pandas - Categorical, which can optionally be turned to sortable with arbitrary order of elements. It is very convenient when order of elements should be fixed and can't be described by any logic.

**Expected behavior**

natsorted should when dealing with ordered categorical columns should just use comparison of elements defined by ordering.

**Environment (please complete the following information):**
 - Python Version: 3.7
 - OS [e.g. Windows, Fedora] ubuntu, macos

**To Reproduce**
```
n [1]: import pandas as pd

# create a series with categorical dtype. Note a special flag 'ordered', 
# most cateoricals are unordered and those are handled by natsort ok,  but not ordered
In [2]: x = pd.Categorical(['a', 'b', 'c', 'b', 'a', 'c'], categories=['c', 'b', 'a'], ordered=True)

In [3]: x.sort_values()
Out[3]:
['c', 'c', 'b', 'b', 'a', 'a']
Categories (3, object): ['c' < 'b' < 'a']

In [4]: from natsort import natsorted

In [5]: natsorted(x)
Out[5]: ['a', 'a', 'b', 'b', 'c', 'c']

# expected output is ['c', 'c', 'b', 'b', 'a', 'a']
```

**Comment by SethMMorton** [comment]
Out of curiosity, why use `natsorted` on a column that is sorted by categorical?  E.g. if `x.sort_values()` already gives the correct answer why choose to try and sort with a different method?

**Comment by arogozhnikov** [comment]
tried to add more details and some comments to the example above

**Comment by arogozhnikov** [comment]
@SethMMorton sorry for dropping the ball, yes I believe this should cover my needs
