### ISSUE TITLE
Incorrect release version

### ISSUE THREAD

**Issue by leoll2** [SethMMorton/natsort#139]
Hello Seth, 
thanks for maintaining this brilliant project.
I see that you've just released a new version 7.2.0 which includes some recent type hinting changes. Such update is to be considered an API change for semantic versioning, as it introduces stricter conditions on the in/out parameters of the exposed function. In other words, some CI builds that rely on the natsort may break when they run mypy checks.
For this reason, I believe 7.2.0 should instead be 8.0.0. What do you think?

**Comment by SethMMorton** [comment]
Sure. I'll release as 8.0.0 then yank 7.2.0.
