### ISSUE TITLE
Request for option to modify case-sensitivity when sorting

### ISSUE THREAD

**Issue by cristianocoelho** [SethMMorton/natsort#14]
Hello, hopefully this is in the right place...

It seems that the library behaves weirdly with string case. For example, A a B b will be sorted as A B a b rather than A a B b, not sure if this is intended or not, but it differs from jquery natural sort so it gives some problems.
An easy fix is to use a lambda which casts the string to lower case but I'm wondering if it is possible to have a setting to change this behaviour.

**Comment by aborruso** [comment]
> There is also a new convenience function (`humansorted`) that

Hi @SethMMorton  , firt of all thank you!

Is there a way to use `humansorted` via cli?

**Comment by aborruso** [comment]
> Is there a way to use `humansorted` via cli?

is it `-l`?

**Comment by SethMMorton** [comment]
>  is it -l?

Yes
