### ISSUE TITLE
Sorting a list of dictionaries when the sort field might or might not have a number

### ISSUE THREAD

**Issue by jonathanstegall** [SethMMorton/natsort#156]
- [x] I have read the [`natsort` documentation](https://natsort.readthedocs.io/en/master/) and the [README](https://github.com/SethMMorton/natsort#natsort), and my question is still not answered

I have a list of dictionaries that are each electoral contests (ex county attorney, county commissioner district 1, etc.). Depending on how users have filtered the list, there might (representative district 2) or might not (governor) be contests that have numbers in them.

I started using natsort originally because, for example, State Representative District 1 should be followed by State Representative District 2 and not by State Representative District 11, and it works really well for that!

Ex:

```python
contests = [
    {
        'id': 'id-MN-27---0405',
        'title': 'County Attorney'
    },
    {
        'id': 'id-MN-27--1-0411',
        'title': 'County Park Commissioner District 1'
    }
]
```

My question is about an example like the above. When I run natsort, it returns an example ordered like this (I'm using a longer list of titles):
- County Park Commissioner District 1
- County Commissioner District 2
- County Park Commissioner District 2
- County Commissioner District 3
- County Park Commissioner District 3
- County Commissioner District 4
- County Park Commissioner District 4
- County Park Commissioner District 5
- County Sheriff
- County Attorney

Ideally, I'd rather it be something like:
- County Attorney
- County Commissioner District 2
- County Commissioner District 3
- County Commissioner District 4
- County Park Commissioner District 1
- County Park Commissioner District 2
- County Park Commissioner District 3
- County Park Commissioner District 4
- County Park Commissioner District 5
- County Sheriff

Is this doable with natsort? I saw a similar question in #134, but ultimately I can't tell if it is applicable since it's not a list of dicts.

If it helps, what I'm doing in Python to get this is (`search` is a string that matches part of a contest's title):

```python
try:
    query_result = Contest.query.join(Result.contests).filter(Contest.title.ilike(search)).all()
except exc.SQLAlchemyError:
    pass

if query_result is not None:
    query_result = natsorted(query_result, key=str)
```

**Comment by SethMMorton** [comment]
The issue is you are using `key=str`. That will make `natsort` sort on the string representation of your dictionary:

```python
>>> a = {
...     'id': 'id-MN-27---0405',
...     'title': 'County Attorney'
... }
>>> str(a)
"{'id': 'id-MN-27---0405', 'title': 'County Attorney'}"
```

Since it seems that the string representation puts the `id` key first, you end up sorting based on the ID. To sort on the title, you need to specify to only look at the title in the sort.

To do this, use `key=lambda x: x["title"]`.
