### ISSUE TITLE
detect Path objects in argument iterable and auto-use ns.P

### ISSUE THREAD

**Issue by anntzer** [SethMMorton/natsort#16]
It'd be nice if natsort autodetects whether its arguments are all Path objects (from the new stdlib's `pathlib`), converted them to strs, and turned on `ns.P` automatically (and possibly `ns.IC` on Windows too).  I don't have a strong opinion of what to do if some arguments are Paths and others are not (I guess this should fail with TypeError since they are not technically comparable).

**Comment by SethMMorton** [comment]
I have fixed this in a recent commit.  I will release as an incremental update (version 3.5.2) in a few days.
