### ISSUE TITLE
RFE:  drop use `m2r2` module

### ISSUE THREAD

**Issue by kloczek** [SethMMorton/natsort#162]
`m2r2` is still not updated for `mistune` 2.x and this module is only to include .md file. into metadata.

**Comment by SethMMorton** [comment]
This is only used to build the documentation, and is not required for a regular install. Can you please articulate what is the ROI in removing this and then spending the effort to include markdown into the documentation in an alternate manner?

**Comment by kloczek** [comment]
On packaging all python modules if it is sphinx documebtation I'm building it as man page.
Using `m2r2` blocks that.
Using `m2r2` is kind of overkill beacuse it is poissible to include file into module descriptin without any addonal modules.

**Comment by SethMMorton** [comment]
When I originally needed to add markdown to rst files this was the only way to do it. Based on what you have said it sounds like there is an alternative way possible. Can you please provide instructions on how to do this, or submit a PR to fix it?

**Comment by kloczek** [comment]
https://stackoverflow.com/questions/46278683/include-my-markdown-readme-into-sphinx

**Comment by kloczek** [comment]
gentle ping .. any update? 🤔

**Comment by SethMMorton** [comment]
Would you be willing to submit a PR? I will not have time for this for a while.

**Comment by SethMMorton** [comment]
Actually, I'll just remove the changelog from the docs, and add a link to the changelog in the repo. Should only take a few minutes.

**Comment by kloczek** [comment]
Yep that works 👍 
Thank you.
