### ISSUE TITLE
compatibility with GNU coreutils sort -n (numeric sort)

### ISSUE THREAD

**Issue by milahu** [SethMMorton/natsort#164]
- [x] I have read the [`natsort` documentation](https://natsort.readthedocs.io/en/master/) and the [README](https://github.com/SethMMorton/natsort#natsort), and my question is still not answered

is natsort compatible with GNU coreutils sort?

a quick check suggests no ...

```py
import sys, natsort
lines = list(sys.stdin)
lines = natsort.natsorted(lines)
sys.stdout.writelines(lines)
```

sort -n

```
$ printf "%s\n" 1 1.1 1.1/ 1/ | LC_ALL=C sort -n 
1
1/
1.1
1.1/
```

natsort.natsorted

```
$ printf "%s\n" 1 1.1 1.1/ 1/ | python -c 'import sys, natsort; lines = list(sys.stdin); lines.sort(); lines = natsort.natsorted(lines); sys.stdout.writelines(lines);' 
1
1.1
1.1/
1/
```

natsort.natsorted(a, alg=natsort.PATH)

```
$ printf "%s\n" 1 1.1 1.1/ 1/ | python -c 'import sys, natsort; lines = list(sys.stdin); lines.sort(); lines = natsort.natsorted(lines, alg=natsort.PATH); sys.stdout.writelines(lines);' 
1/
1
1.1/
1.1
```

natsort.os_sorted

```
$ printf "%s\n" 1 1.1 1.1/ 1/ | python -c 'import sys, natsort; lines = list(sys.stdin); lines.sort(); lines = natsort.os_sorted(lines); sys.stdout.writelines(lines);' 
1/
1
1.1/
1.1
```

alternatives

- https://stackoverflow.com/questions/4836710/is-there-a-built-in-function-for-string-natural-sort

**Comment by SethMMorton** [comment]
`natsort` makes no guarantee nor attempt to sort like GNU coretools.

**Comment by SethMMorton** [comment]
Did you try `realsorted` or `ns.FLOAT`, *without* `ns.PATH`? I wager that will get you what you want. `ns.PATH` likely sees e.g. `1` and `1/` as degenerate because it splits the input on `/`.

**Comment by milahu** [comment]
`natsort.realsorted` gives a different result than `sort -n`

```
$ a=$(printf "%s\n" 1 1.1 1.1/ 1/ 1.01 1.1.1 1.01.1 1.1.01 1.01.01); paste <(echo "sort -V"; echo "$a" | sort -V) <(echo "natsort.realsorted"; echo "$a" | python -c 'import sys, natsort; lines = list(sys.stdin); lines.sort(); lines = natsort.realsorted(lines); sys.stdout.writelines(lines);') | column -t -o"|" -s$'\t'

sort -V|natsort.realsorted
1      |1
1.01   |1/
1.1    |1.01.01
1.01.01|1.01.1
1.01.1 |1.01
1.1.01 |1.1.01
1.1.1  |1.1.1
1.1/   |1.1
1/     |1.1/
```

on more thought, i will use [version sort](https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python) (GNU coreutils: `sort -V`), because there are no floats in my strings

`natsort.natsorted` gives a different result than `sort -V`

```
$ a=$(printf "%s\n" 1 1.1 1.1/ 1/ 1.01 1.1.1 1.01.1 1.1.01 1.01.01 0 1.1rc1 1.1rc2 1.1-rc1 1.1-rc2 1.1pre1 1.1a 1.1b a aa aaa ab abb aab b); paste <(echo "sort -V"; echo "$a" | sort -V) <(echo "natsort.natsorted"; echo "$a" | python -c 'import sys, natsort; lines = list(sys.stdin); lines.sort(); lines = natsort.natsorted(lines); sys.stdout.writelines(lines);') | column -t -o"|" -s$'\t'

sort -V|natsort.natsorted
0      |0
1      |1
1.01   |1.01
1.1    |1.1
1.1a   |1.1-rc1
1.1b   |1.1-rc2
1.1pre1|1.01.01
1.1rc1 |1.01.1
1.1rc2 |1.1.01
1.1-rc1|1.1.1
1.1-rc2|1.1/
1.01.01|1.1a
1.01.1 |1.1b
1.1.01 |1.1pre1
1.1.1  |1.1rc1
1.1/   |1.1rc2
1/     |1/
a      |a
aa     |aa
aaa    |aaa
aab    |aab
ab     |ab
abb    |abb
b      |b
```

feel free to close this as "out of scope"

**Comment by milahu** [comment]
fixed in https://github.com/matan1008/pygnuutils/issues/12

PR welcome?
there are many versions of natural sort / version sort, and having the GNU version would be nice

**Comment by SethMMorton** [comment]
> but that is wrong too

I would be very careful about labeling a sort order as "wrong". Even the GNU manual that you quoted states this: _"there is no one correct way or universally agreed-upon way to order items. Each program and each programming language can decide its own ordering algorithm and call it “version sort”, “natural sort”, or other names."_  Telling a package author that their code is wrong when it doesn't match a choice made by another author (when both authors agree the choice is arbitrary) is not really the best way to initiate an interaction.

**Comment by SethMMorton** [comment]
> PR welcome?
> there are many versions of natural sort / version sort, and having the GNU version would be nice

*In general*, I don't like to add more options to `natsort` because it already has too many options, and in general one can perform any customization they want using the `key` argument. Additionally, most requests are a bit subjective, and I don't like introducing subjectivity in results. I usually prefer to add an entry to the "examples" if it is possible to use `key` instead of changing the library itself.

However, in this case the request is objective: does it or does it not sort like GNU coretools? 

If it is possible to use `key`, I think I would rather go in that direction, but if not I think adding this functionality would be OK.

**Comment by milahu** [comment]
well ... `pygnuutils` is objectively wrong when compared to `sort --version-sort`
there is no nice way to say that ; )

> perform any customization they want using the `key` argument

i would add

- `natsort.gnuversioncmp` for comparison
- `natsort.gnuversionsorted` for out-place sorting (optional)
- `natsort.gnuversionkey` for out-place/in-place sorting (optional)

```py
x = natsort.gnuversioncmp("1.0", "1.1") # comparison
a = ["1.0", "1.1"]
a = natsort.gnuversionsorted(a) # out-place sorting
a = sorted(a, key=natsort.gnuversionkey) # out-place sorting
a.sort(key=natsort.gnuversionkey) # in-place sorting
```

`sorted` and `key` are optional, because they are trivial to derive from `cmp`

**Comment by SethMMorton** [comment]
I am feeling hesitant because I am questioning if `natsort` needs this. I only added the `os_sorted` method because so many people wanted it. I have never gotten a request for GNU-compatible sorting before - I wonder how useful the feature would actually be. I also don't want to compete with `pygnuutils` if they already implement it - could people use that library to achieve the same thing?

**Comment by milahu** [comment]
> could people use that library to achieve the same thing?

yes, but ...

- pygnuutils does more than sorting
- pygnuutils is less popular than natsort (4 vs 740 stars)
- pygnuutils feels undermaintained to me
- GNU version-sort is one variant of natsort
- adding 100 SLOC to natsort wont hurt anyone

**Comment by milahu** [comment]
pygnuutils was fixed in https://github.com/matan1008/pygnuutils/pull/13, so feel free to close this

**Comment by SethMMorton** [comment]
>  adding 100 SLOC to natsort wont hurt anyone

Well, except for me, who will have to maintain it (plus tests).

---

Given that there is already a solution in `pygnuutils`, I would be willing to do one of the two following actions (in order of preference):

- Add to the examples and recipes wiki page that people wanting to sort like GNU utilities should use `pygnuutils`, and provide a specific code example
- Add a `gnusorted` method that uses `pygnuutils` under the hood, and make it optional to install e.g. `pip install natsort[gnu]`.

**Comment by milahu** [comment]
> Add a `gnusorted` method that uses `pygnuutils` under the hood

thats really the worst option

> Add to the examples and recipes wiki page

imho this issue is good enough

anyway, thanks for the chat, do as you wish : )

**Comment by SethMMorton** [comment]
I've been giving it some thought. Go ahead and make a PR for this. I think I'm OK with it.

**Comment by SethMMorton** [comment]
I assume since no PR has popped up that none is coming. I will close this issue.
