### ISSUE TITLE
wiki pages so huge that they are not loaded properly

### ISSUE THREAD

**Issue by Enissay** [SethMMorton/natsort#169]
**Describe the feature or enhancement**
wiki pages so huge that they are not loaded properly
![image](https://github.com/SethMMorton/natsort/assets/794673/ca54e67a-45d6-43ec-b757-0ce482552be0)

**Provide a concrete example of how the feature or enhancement will improve `natsort`**
Break these huge sections/pages into smaller sub-sections/pages that make sense of course...

**Would you be willing to submit a Pull Request for this feature?**
I just discovered `natsort`, for sure once I am better at it, I will suggest a better structure of the wiki!

**Comment by SethMMorton** [comment]
Huh, that is strange. It used to work - I imagine something has changed with how GitHub is serving these pages. I'll see what I can do.

**Comment by SethMMorton** [comment]
Fixed - I split it into two and kept the old page name as a landing page.
