### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by bersbersbers** [SethMMorton/natsort#173]
https://pypi.org/project/natsort/ says

> Programming Language
[Python](https://pypi.org/search/?c=Programming+Language+%3A%3A+Python)
[Python :: 3](https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3)
[Python :: 3.7](https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3.7)
[Python :: 3.8](https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3.8)
[Python :: 3.9](https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3.9)
[Python :: 3.10](https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3.10)
[Python :: 3.11](https://pypi.org/search/?c=Programming+Language+%3A%3A+Python+%3A%3A+3.11)

Would be good to declare support for Python 3.12

**Comment by SethMMorton** [comment]
Python 3.12 is supported - that list just doesn't mention it.

**Comment by SethMMorton** [comment]
I just updated this list in `main`, but I don't anticipate making a release just so it shows up on PyPI - I'll wait till there actual changes before pushing.
