### ISSUE TITLE
Wrong sorting order with grouped numbers

### ISSUE THREAD

**Issue by exostor** [SethMMorton/natsort#19]
natsort 3.5.2, python 3.2.3

    >>> l=["li1-1", "li1-2", "li1-3", "li1-10", "li2-11", "li10-1", "li2-11b", "li2-11a", "li2-1b11", "li2-1b2"]
    >>> natsort.natsorted(l)
    ['li1-10', 'li1-3', 'li1-2', 'li1-1', 'li2-11', 'li2-11a', 'li2-11b', 'li2-1b2', 'li2-1b11', 'li10-1']

But I expected the result:

    ['li1-1', 'li1-2', 'li1-3', 'li1-10', 'li2-1b2', 'li2-1b11', 'li2-11', 'li2-11a', 'li2-11b', 'li10-1']

**Comment by SethMMorton** [comment]
Use either `versorted(l)` or `natsorted(l, alg=ns.UNSIGNED)`

**Comment by exostor** [comment]
Aha, I didn't see my case as version numbers, but yes, it works perfecly. Thanks!

**Comment by SethMMorton** [comment]
@exostor As of `natsort` version 4.0.0, you don't need to use `versorted` or `ns.UNSIGNED` anymore.
