### ISSUE TITLE
FYI Python 3 "unorderable types" error bypassed by TYPESAFE

### ISSUE THREAD

**Issue by tallforasmurf** [SethMMorton/natsort#23]
Here's another I just found. However, using TYPESAFE corrects it.

    kfunc = natsort.natsort_keygen( alg=( natsort.ns.LOCALE ) )
    sorted( [ '10-12','10th'], key=kfunc)
    Traceback (most recent call last):
      File "<string>", line 1, in <fragment>
        builtins.TypeError: unorderable types: bytes() < float()
    ksafe = natsort.natsort_keygen(alg=(natsort.ns.LOCALE|natsort.ns.TYPESAFE))
    sorted( [ '10-12','10th'], key=ksafe)
    ['10-12', '10th']

I am slightly concerned because I noted a comment in the code about TYPESAFE being in some way expensive to execute and I am sorting quite large tables.

**Comment by SethMMorton** [comment]
Yes, the `TYPESAFE` method was added to prevent exactly this problem.  If you don't need to account for signed numbers, you can use `UNSIGNED` and you shouldn't need to use `TYPESAFE`; you won't get any performance penalty - in fact, if you move to `UNSIGNED | INT` the number searching is the fastest.  

Note that in natsort >= 4.0.0, the default sorting algorithm will be `UNSIGNED | INT`, so this problem will go away.

**Comment by SethMMorton** [comment]
Also, if you are concerned about speed, you should install https://pypi.python.org/pypi/fastnumbers.

**Comment by SethMMorton** [comment]
BTW, is there a reason you aren't just using `natsorted` rather than generating the keys with `natsort_keygen`? I ask because `natsorted` takes care of the `TYPESAFE` problem for you, and only turns it on if needed.

**Comment by tallforasmurf** [comment]
Thanks for being so prompt & helpful! Without going into too much depth, I am using the keyfunc with a sortedcontainers.SortedDict, to control the implicit ordering of SortedDict. The base SortedDict is the data model behind a Qt TableView. Always I want alg=LOCALE because some users are working in French and want their Ás sorted next to their As which native Python doesn't do. Also when the user clicks on a table heading, indicating a desire to sort ascending or descending on that column,  I query a "Respect Case" checkbox and make a new SortedDict using a key_func with or without IGNORECASE.

**Comment by tallforasmurf** [comment]
Hi. Replying to an old issue instead of starting a new one, because I think
it is working as intended!

Unfortunately that is a problem. I have code that assumes, when a table is
sorted with Respect Case on, that all the Uppercase-initial words will sort
together, and lowercase-initial together. This is what you refer to (in the
doc for LOWERCASEFIRST) as "the default from a purely ordinal sort" --
[Apple, Banana, apple, banana].

With LOCALE, which I definitely need, the only difference between having
IGNORECASE and not having it, is the order within pairs,
[Apple,apple,Banana,banana] vs. [apple,Apple,banana,Banana].

I'd really like to have my LOCALE cake and still eat my ordinal case
sequence too -- is there any way?

Thanks for your time,
Dave Cortesi

**Comment by SethMMorton** [comment]
Unfortunately, this is not possible because it is the locale/PyICU library that is dictating the order when you use LOCALE so I am not sure it would be possible to force it to not group the letters in that manner.

**Comment by SethMMorton** [comment]
You could try sorting twice.  The first time, use `natsort` with `LOCALE`, and then the second time use python's built in sort with the `itemgetter` function from the `operator` module to sort on the first letter using ordinal sorting.  Because sorting is guaranteed to be stable in python, within each letter your order will be maintained, and the order of the first letters will be what you want.

```python
>>> from natsort import natsorted, ns
>>> from operator import itemgetter
>>> a = ['Apple',  'c1', 'Banana', 'apple',  'c14', 'banana', 'C4', 'Apples', 'C30', 'Applu','c2']
>>> sorted(natsorted(a, alg=ns.LOCALE), key=itemgetter(0))
>>> ['Apple', 'Apples', 'Applu', 'Banana', 'C4', 'C30', 'apple', 'banana', 'c1', 'c2', 'c14']
```

I realize this may not be desirable since you will have to sort twice, but I don't believe I could support this within the `natsort` library.

**Comment by tallforasmurf** [comment]
Thanks for your as-always prompt & helpful reply.

**Comment by SethMMorton** [comment]
I would like to highlight that you will run into issues if the first character is a digit, because that will ruin the order that `natsort` created for those entries.  If that cannot be the case, this should be a safe method.

**Comment by SethMMorton** [comment]
I was mistaken before when saying that I could not support this in the `natsort` library.  It would require adding an additional option, probably `UNGROUPLETTERS` which would only mean anything if `LOCAL` was enabled.

I'm not sure if I will get a chance to do it for a few days, so if you want here is the diff to add the ability to do what you want without sorting twice; you can add it to your local copy for now.  This implementation will force LOCAL to sort the way you want always, so it will be more flexible than a real implementation later. This also will gracefully handle when numbers are at the start of a string so my previous warning there would be void.

```diff
diff --git a/natsort/utils.py b/natsort/utils.py
index 0eb5302..a9d6759 100644
--- a/natsort/utils.py
+++ b/natsort/utils.py
@@ -275,6 +275,8 @@ def _natsort_key(val, key, alg):
                 val = val.swapcase()
             if alg & _ns['IGNORECASE']:
                 val = val.lower()
+            if use_locale and val[0] == val[0].upper():
+                val = b' ' + val if isinstance(val, bytes) else ' ' + val
             return tuple(_number_extracter(val,
                                            regex,
                                            num_function,
```

**Comment by SethMMorton** [comment]
Please check out issue #26 and the latest version on PyPI for this fix.

**Comment by SethMMorton** [comment]
Hello from the future.  ``TYPESAFE`` is no longer required as of version 5.0.0 because this functionality is now always on without speed penalty due to a new internal structure of the code.  If you add this it will now do nothing.
