### ISSUE TITLE
Python 3 unorderable types with natsort_keygen

### ISSUE THREAD

**Issue by Rendaw** [SethMMorton/natsort#28]
This seems to be changed behavior since python 2.
```python
>>> x = natsort.natsort_keygen()
>>> x('a.1.1.b')
('a', 0.1, 0.1, '.b')
>>> x('a.1.b')
('a', 0.1, '.b')
>>> x('a.1.1.b') < x('a.1.b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: float() < str()
```

`natsort.natsorted` works fine, but sorted with `key=x` (same `x` as above) gives `unorderable types`.

I'm implementing a custom multilevel sort so I don't think I can use `natsort.natsorted`, unfortunately.

**Comment by Rendaw** [comment]
Sorry, as noted at https://github.com/SethMMorton/natsort/issues/23 this is resolved by using `natsort_keygen(alg=natsort.ns.TYPESAFE)`.

Thanks for this excellent project!

**Comment by SethMMorton** [comment]
Which version of natsort are you using?  With the newest version I wouldn't expect you to need TYPESAFE for those inputs.

**Comment by Rendaw** [comment]
I apologize again, I was also on 3.5.3.  As you suggested, 4.0.1 works without `alg=` specified.

**Comment by SethMMorton** [comment]
FYI: Now, as of version 5.0.0 ``TYPESAFE`` is never needed to be added because it is always on.
