### ISSUE TITLE
Missing file in running tests in natsort-4.0.1

### ISSUE THREAD

**Issue by idella** [SethMMorton/natsort#31]
The tarball is missing the file test_natsort/slow_splitters.py. It is missing from MANIFEST.in.
Also missing is folder compat and its contents.

**Comment by SethMMorton** [comment]
Are you actually referring to version 4.0.2?  If so, please see #30.  There is not supposed to be a `compat `folder in the version 4.0.1 release, so I'm a bit confused about what you are referring to.  However, I do acknowledge that the `slow_splitters` file is missing from that release, but is there a reason you aren't using version 4.0.3?

**Comment by SethMMorton** [comment]
Since this report is about an older version of natsort, and recent versions have been released that specifically address the mentioned issue, I am going to close this issue.

**Comment by idella** [comment]
Purely as a courtesy, out page that lists new releases is flawed.  See
euscan.gentooexperimental.org/herds/ and you will note it lists 4.0.1 . We have been caught out with many similar cases. Now I know there is a release 4.0.3 I will bump it in portage accordingly.
