### ISSUE TITLE
'NoneType' object has no attribute 'format'

### ISSUE THREAD

**Issue by TheML9I** [SethMMorton/natsort#38]
If you use uwsgi with parameter optimize=2 you can get error with using it:

> AttributeError at /mymodule/api/
> 'NoneType' object has no attribute 'format'

interpreter info:

> Python Executable:	/home/httpd/app/bin/uwsgi
> Python Version:	2.7.5

additional:

> -O Turn on basic optimizations. This changes the filename extension for compiled (bytecode) files from .pyc to .pyo. See also PYTHONOPTIMIZE.
-OO Discard docstrings in addition to the -O optimizations.

As possible solution add for py23compat.py

`
return s.format(u='u') if s else s
`

Any ideas?

Thnx!

**Comment by SethMMorton** [comment]
You are removing function docstrings with an optimization flag, and this is causing errors with the compat code because it expects docstrings to exist. Do I understand your issue correctly?  If so, this seems like it will be a straightforward fix.

**Comment by SethMMorton** [comment]
As a side note, the `py23compat.py` file hasn't existed in `natsort` since version 4.0.1... version 4.0.3 was released almost a year ago, and there is now version 5.0.0.  Is there a reason you haven't upgraded?

**Comment by SethMMorton** [comment]
Version 5.0.1 incorporates this update.

**Comment by TheML9I** [comment]
You're right. 

We're using ver. 3.5 in our local PYPI. But we checked ver. 5 installed from common PYPI and had similar error. I think your [last fix](https://github.com/SethMMorton/natsort/commit/aaba1bf8227209d7640eba6de43438940a84d907) solve it. As soon as possible i check it! Thanks!
