### ISSUE TITLE
'setup.py test' doesn't run any tests

### ISSUE THREAD

**Issue by yurivict** [SethMMorton/natsort#46]
```
Ran 0 tests in 0.000s

OK
```

Found on FreeBSD, running ```make test``` in the port.

**Comment by SethMMorton** [comment]
Yes, this is the intended behavior.  `natsort` uses [tox](https://tox.readthedocs.io/en/latest/) to set up the testing environment, and [pytest](https://docs.pytest.org/en/latest/) to run the actual tests.

Does the FreeBSD port support running python unit tests with anything besides `python setup.py test`? If so, might I recommend that they update to something like `python -m pytest`?

**Comment by SethMMorton** [comment]
I supposed it would be helpful if the README included a line or two on how to run the tests.  Right now I guess I am making the assumption that someone would see the `tox.ini` and use `tox`.

**Comment by yurivict** [comment]
Yes, please add this to documentation.
Also, it appears that ```pathlib``` is missing from the list of dependencies.

**Comment by SethMMorton** [comment]
`pathlib` is only *required* for testing, as such it is only listed in [`testing-requirements.txt`](https://github.com/SethMMorton/natsort/blob/master/testing-requirements.txt).  I will make sure the documentation makes it clear what each of the requirements files are for.
