### ISSUE TITLE
Feature request natsorted():  Sort by letters, then numbers

### ISSUE THREAD

**Issue by NtwkEngineer** [SethMMorton/natsort#48]
I'd like to submit a feature request to add an option that would allow natsorted() to sort by letters first, then numbers instead of numbers first, then letters.  Here is an example of the list that I am looking to sort - I am sorting by index 2 ('ABCDE', 'BCDEF' and '10001'):

```python
from natsort import natsorted
a = [
	['192.168.1.1', 'generic_description_1', 'ABCDE', 'apples', '172.16.1.1', u'\nCircuit is up\n'],
	['192.168.1.1', 'generic_description_2', 'BCDEF', 'oranges', '172.16.2.1', u'\nCircuit is up\n'],
	['192.168.2.1', 'generic_description_3', '10001', 'bananas', '172.16.3.1', u'\nCircuit is up\n']
]
print(natsorted(a, key = lambda x: x[2]))
```

Here are the results that are printed:

```
[['192.168.2.1', 'generic_description_3', '10001', 'bananas', '172.16.3.1', u'\nCircuit is up\n'],
 ['192.168.1.1', 'generic_description_1', 'ABCDE', 'apples', '172.16.1.1', u'\nCircuit is up\n'],
 ['192.168.1.1', 'generic_description_2', 'BCDEF', 'oranges', '172.16.2.1', u'\nCircuit is up\n']]
```

And as you can see, it sorts by index 2 by numbers first, then letters:

10001
ABCDE
BCDEF

The option I am requesting would allow the sorting by letters first, then numbers - like this:

ABCDE
BCDEF
10001

Thanks for the consideration!

-Matt

**Comment by NtwkEngineer** [comment]
And I'm sorry - I meant "index 2" through all of this, not "index 3".

**Comment by SethMMorton** [comment]
This is a good request.  The only reason `natsort` puts numbers first is that it was the easier thing to do and I made the assumption that that is what users would want.  The process of maintaining this library has taught me that either my assumptions are always wrong, or not to make assumptions.

**Comment by NtwkEngineer** [comment]
Hi Seth!

Works great with my production data.  Thanks so much for the fast implementation of this request! :)

-Matt
