### ISSUE TITLE
Errors when sorting test with CRLF line endings

### ISSUE THREAD

**Issue by AlisterH** [SethMMorton/natsort#59]
Hi, natsort certainly gives better results than coreutils `sort -V`, or anything I can get out of `msort`.
But it seems that it makes some mistakes when the input is from a file with  Windows line endings (i.e. CRLF) - see below.

Or perhaps there is something obvious that I'm missing (I guess something about what cat does)?
It seems that coreutils `sort -V` also gives worse results when operating on CRLF files.  The Python natsort doesn't seem to.
````
$  cat test3|/usr/local/bin/natsort
Callisto Morphamax 6000 SE
Callisto Morphamax 6000 SE2

$  cat test.txt|/usr/local/bin/natsort

Callisto Morphamax 6000 SE2
Callisto Morphamax 6000 SE

$  diff test3 test.txt
1,2c1,2
< Callisto Morphamax 6000 SE
< Callisto Morphamax 6000 SE2
---
> Callisto Morphamax 6000 SE
> Callisto Morphamax 6000 SE2

$  file test3
test3: ASCII text

$  file test.txt
test.txt: ASCII text, with CRLF line terminators

**Comment by AlisterH** [comment]
> better results than ... anything I can get out of msort

Actually, this bit might be wrong - I can't figure out what input I was testing msort with that gave bad results.
Everything I'm testing natsort with now seems to give identical results using `msort -l -w -c h`.  And it seems to be affected by the CRLF in exactly the same way.

**Comment by SethMMorton** [comment]
I am very surprised that these would give different results - [`natsort` removes all trailing whitespace from the input before doing any sorting](https://github.com/SethMMorton/natsort/blob/5.3.2/natsort/__main__.py#L96). 

It might be instructive to see what the files look like in raw form, something like opening the file and showing the `repr` - I did this on my own file with non-printable characters to see what's happening under the hood:

```
$ cat test.txt 
TUPLE        LOGFILE STATUS       FSDB STATUS                   
Check_5          $ 
$ python -c "print(repr(open('test.txt').read()))"
'TUPLE        LOGFILE STATUS       FSDB STATUS                   \nCheck       \x08\x08\x08\x08\x08\x08\x08_5          '
```

**Comment by AlisterH** [comment]
````
python -c "print(repr(open('test.txt').read()))"
'Callisto Morphamax 6000 SE\r\nCallisto Morphamax 6000 SE2\r\n'
python -c "print(repr(open('test3.txt').read()))"
'Callisto Morphamax 6000 SE\nCallisto Morphamax 6000 SE2\n'

**Comment by SethMMorton** [comment]
I am unable to replicate what you are seeing on my machine (OSX) so the following information will be helpful: 

 - What is your OS? 
 - Do you get the same results with `cat test.txt | natsort` as with `natsort < test.txt`?
 - Do you get the same results with `cat test.txt | tr -d "\r" | natsort`?  (the `tr -d "\r"` removes all carriage returns)
 - Against what version of python did you install `natsort`?
 - What version of `natsort` are you using? (`natsort --version`)
 - Are the results what you expect?
 - Do you get the same results if you execute the following one-liner: `python -c "import natsort, sys; print(natsort.natsorted([x.strip() for x in open(sys.argv[1])]))" test.txt`

**Comment by AlisterH** [comment]
Oh, I'm so sorry - somehow in moving between devices I've managed to file a ticket against the wrong natsort.

This problem is with the C natsort (as well as coreutils sort).  As I alluded to, I installed the python natsort to compare results and yes, it produces the correct results.
