### ISSUE TITLE
Python 3.7 Release

### ISSUE THREAD

**Issue by tilgovi** [SethMMorton/natsort#62]
I'm using natsort in a project and I'd like to make it Python 3.7 compatible. The current master works just fine after the StopIteration fix. Is there anything I can do to help get it on PyPI?

**Comment by SethMMorton** [comment]
Natsort should work fine on Python 3.7 even without the fix - the issue was in the test itself, not in the production code.

I'll make a patch release tomorrow that includes the fixed tests.

**Comment by tilgovi** [comment]
Ah, thanks! You're correct. I had been on 5.0.2 and noticed a StopIteration when I upgraded, but you fixed that a while back.

**Comment by SethMMorton** [comment]
The above change was made with advice from https://github.com/travis-ci/travis-ci/issues/9815, since Python 3.7 support is not working out-of-the-box on Travis-CI quite yet.

**Comment by tilgovi** [comment]
Make sense! 🙌
