### ISSUE TITLE
'extras_require' must be a dictionary whose values are strings or lists

### ISSUE THREAD

**Issue by jondkelley** [SethMMorton/natsort#64]
## Minimum, Complete, Verifiable Example

* CentOS Linux 7.5
* Python 2.7.5
* Centos 7 package: python-setuptools 0.9.8 (latest from Redhat 7, added Apr 12, 2017)

Create a setup.py with natsort required:

    # -*- coding: utf-8 -*-
    # !/usr/bin/python

    import sys

    from setuptools import setup

    sys.path.insert(0, '.')

    if __name__ == "__main__":
        package = "test_bug"
        setup(
            name=package,
            version="0.0.1",
            author="Nobody",
            author_email="nobody@aol.com",
            url="https://github.com/SethMMorton",
            license="ASLv2",
            packages=[package],
            package_dir={package: package},
            description=(
                'test'
            ),
            long_description=(
                'test'
            ),
            classifiers=[
                'Intended Audience :: System Administrators',
            ],
            data_files=[],
            install_requires=[
                'natsort'
            ]
        )

Run command

    /usr/bin/python2.7 setup.py install

## Error message, Traceback, Desired behavior, Suggestion, Request, or Question

    Processing dependencies for test_bug==0.0.1
    Searching for natsort
    Reading https://pypi.python.org/simple/natsort/
    Best match: natsort 5.3.3
    Downloading https://files.pythonhosted.org/packages/9b/04/f397de5d77942e37cf31f2d37ba7cc2b6f46a440e5dd41e3ab3474f51a0e/natsort-5.3.3.tar.gz#sha256=da930bfddce941526955dea8d35a44243c96adf919ceb758ba7bbd1ba5b0a39a
    Processing natsort-5.3.3.tar.gz
    Writing /tmp/easy_install-QQ9Rgf/natsort-5.3.3/setup.cfg
    Running natsort-5.3.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-QQ9Rgf/natsort-5.3.3/egg-dist-tmp-mM234_
    error: Setup script exited with error in natsort setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

**Comment by jondkelley** [comment]
If the dev team doesn't think this is a problem, this can be resolved by 

    pip2.7 install --upgrade setuptools

on Centos 7. It's interesting to me Redhat offers no upgrade path for a modern python-setuptools.

**Comment by SethMMorton** [comment]
What version of setuptools was being used?

**Comment by SethMMorton** [comment]
@jondkelley FYI, `natsort` version 5.5.0 was just released that supports older `setuptools` versions, so you shouldn't have to update to install `natsort` anymore.
