### ISSUE TITLE
Test test_input_string_transform_factory_removes_thousands_separator_and_is_float_aware_with_LOCALE_and_FLOAT_example is failing on last release 5.3.3

### ISSUE THREAD

**Issue by agustinhenze** [SethMMorton/natsort#65]
Hi there, I'm the debian maintainer of this module :). I was packaging last version and I can repeat in a controlled environment the test mentioned on the subject is failing for both Python versions. Python2.7 and Python3.6.

```
=================================== FAILURES ===================================
 test_input_string_transform_factory_removes_thousands_separator_and_is_float_aware_with_LOCALE_and_FLOAT_example 
test_natsort/test_input_string_transform_factory.py:126: in test_input_string_transform_factory_removes_thousands_separator_and_is_float_aware_with_LOCALE_and_FLOAT_example
    assert _input_string_transform_factory(ns.LOCALE | ns.FLOAT)(x) == '12543642642.534,534980'
E   AssertionError: assert '12,543,642,642.534,534,980' == '12543642642.534,534980'
E     - 12,543,642,642.534,534,980
E     ?   -   -   -           -
E     + 12543642642.534,534980
```

You can see the detailed log here

https://salsa.debian.org/debian/natsort/-/jobs/40303

**Comment by SethMMorton** [comment]
What is your `LOCALE` set to?  While cleaning up the test suite recently, I noticed that the tests that use `locale` were making the assumption that the `locale` was `"C"` or `"en_US"`.  If that is not the case for you it would explain the failure.

**Comment by agustinhenze** [comment]
Hi @SethMMorton locale is unset :man_shrugging:.

```python
In [1]: import locale

In [2]: locale.getdefaultlocale()
Out[2]: (None, None)
```
So we found the failure, thanks! :)

**Comment by SethMMorton** [comment]
I will update the tests to not make any assumptions about the environment.

**Comment by SethMMorton** [comment]
Is it possible for you to try running the tests as of c749c7991cb72bdd4625c78a4cd31356f77d535c (branch "clarify-code-and-simplify-tests")? All tests using `LOCALE` should be explicitly setting a locale.

**Comment by SethMMorton** [comment]
Does this still give you problems on 5.4.0?

**Comment by agustinhenze** [comment]
Hi @SethMMorton, sorry for the delay. I've packaged last version and it works fine :). [Here](https://salsa.debian.org/debian/natsort/-/jobs/46405) you can see the output for the tests. So, I'm closing this issue. Thank you very much!
